name: Testing JSON secrets and Deploy to Streamlit

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  ENCODED_PIPELINE_SECRET: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

jobs:
  secrets:
    name: Accessing Google Cloud Secret
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Envs Before
        run: echo "Env values before"

      - name: Decode and Authenticate with Google Cloud
        run: |
          # Decode the base64-encoded secret and save it to a JSON file
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > $HOME/google-credentials.json
          
          # Authenticate with Google Cloud using the decoded JSON credentials
          gcloud auth activate-service-account --key-file=$HOME/google-credentials.json

  deploy:
    name: Deploy to Streamlit Cloud
    runs-on: ubuntu-latest
    needs: secrets  # Ensure this job only runs after the secrets job completes successfully
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Deploy to Streamlit Cloud
        run: |
          # If you're using Streamlit Cloud, this step may not be necessary.
          # Streamlit Cloud auto-deploys from GitHub, but you can trigger deployment via API or script here if needed.
          echo "Your app is deployed to Streamlit Cloud automatically with GitHub push to the main branch."